apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
    - name: test-container
      image: busybox
      command: [ "/bin/sh", "-c", "env; while true; do sleep 3600; done"]
      env:
      - name: JSON_CONFIG
        valueFrom:
          configMapKeyRef:
            name: my-configmap
            key: config.json 
      - name: APP_PORT
        valueFrom:
          configMapKeyRef:
            name: my-configmap
            key: portNumber
      - name: MARCIN_VAR
        value: MARCIN_VALUE
      envFrom:
        - configMapRef:
            name: from-env-file 

