apiVersion: v1
kind: Pod
metadata:
  name: configmap-volume-pod
spec:
  volumes:
    - name: app-config
      configMap:
        name: another-cm
  containers:
    - name: test-container
      image: busybox
      command: [ "/bin/sh", "-c", "while true; do sleep 3600; done"]
      volumeMounts:
      - mountPath: /data
        name: app-config
